Revert "Fix install on linux "

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -44,18 +44,7 @@ install_aria2() {
   (
     echo "∗ Downloading and installing aria2..."
     curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
-
-    if [[ $OSTYPE =~ linux ]]; then
-
-      cd "$install_path" || exit 1
-
-      tar -xjf "$source_path" --strip-components=1 || fail "Could not uncompress"
-      ./configure --prefix "$install_path"
-      make
-      make install
-    else
-      tar -xjf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
-    fi
+    tar -xjf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
     echo "The installation was successful!"
     rm "$source_path"
   ) || (
