run shfmt with params from github action

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -18,50 +18,50 @@
 set -eo pipefail
 
 fail() {
-	echo -e "\e[31mFail:\e[m $*"
-	exit 1
+  echo -e "\e[31mFail:\e[m $*"
+  exit 1
 }
 
 install_aria2() {
-	local install_type=$1
-	local version=$2
-	local install_path=$3
+  local install_type=$1
+  local version=$2
+  local install_path=$3
 
-	if [ "$install_type" != "version" ]; then
-		fail "asdf-aria2 supports release installs only"
-	fi
+  if [ "$install_type" != "version" ]; then
+    fail "asdf-aria2 supports release installs only"
+  fi
 
-	local download_url
+  local download_url
 
-	case "$OSTYPE" in
-	darwin*) download_url="https://github.com/aria2/aria2/releases/download/release-${version}/aria2-${version}-osx-darwin.tar.bz2" ;;
-	linux*) download_url="https://github.com/aria2/aria2/releases/download/release-${version}/aria2-${version}.tar.bz2" ;;
-	*) fail "Unsupported platform" ;;
-	esac
+  case "$OSTYPE" in
+    darwin*) download_url="https://github.com/aria2/aria2/releases/download/release-${version}/aria2-${version}-osx-darwin.tar.bz2" ;;
+    linux*) download_url="https://github.com/aria2/aria2/releases/download/release-${version}/aria2-${version}.tar.bz2" ;;
+    *) fail "Unsupported platform" ;;
+  esac
 
-	local source_path="${install_path}/bin/aria2.tar.bz2"
+  local source_path="${install_path}/bin/aria2.tar.bz2"
 
-	(
-		echo "∗ Downloading and installing aria2..."
-		curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
+  (
+    echo "∗ Downloading and installing aria2..."
+    curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
 
-		if [[ "$OSTYPE" =~ linux ]]; then
+    if [[ $OSTYPE =~ linux ]]; then
 
-			cd "$install_path" || exit 1
+      cd "$install_path" || exit 1
 
-			tar -xjf "$source_path" --strip-components=1 || fail "Could not uncompress"
-			./configure --prefix "$install_path"
-			make
-			make install
-		else
-			tar -xjf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
-		fi
-		echo "The installation was successful!"
-		rm "$source_path"
-	) || (
-		rm -rf "$install_path"
-		fail "An error occurred"
-	)
+      tar -xjf "$source_path" --strip-components=1 || fail "Could not uncompress"
+      ./configure --prefix "$install_path"
+      make
+      make install
+    else
+      tar -xjf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
+    fi
+    echo "The installation was successful!"
+    rm "$source_path"
+  ) || (
+    rm -rf "$install_path"
+    fail "An error occurred"
+  )
 }
 
 install_aria2 "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
